### ISSUE TITLE
virtio-net: support device stats

### ISSUE THREAD

**Issue by fengidri** [oasis-tcs/virtio-spec#180]
In the device implementation, we can count a lot of such information,
which can be used for debugging and judging the running status of the
device. We hope to directly display it to the user through ethtool.

Patch Link： https://lists.oasis-open.org/archives/virtio-comment/202310/msg00047.html

**Comment by cohuck** [comment]
BALLOT CREATED AT URL: https://www.oasis-open.org/committees/ballot.php?id=3801

**Comment by davidarinzon** [comment]
Hi
Following the discussion in https://lore.kernel.org/netdev/20240827110402.0c8c5fc6@kernel.org/T/#m7bdfbb1da72b391cb9cbf69a7bed973142a543bc

The used ratelimit counters `rx-hw-drop-ratelimits` and `tx-hw-drop-ratelimits (uint)` which are specified in https://docs.kernel.org/next/networking/netlink_spec/netdev.html and are implemented by the virtio driver in https://elixir.bootlin.com/linux/v6.11-rc6/source/drivers/net/virtio_net.c#L257 are counting drops due to exceeding the limit.

It was mentioned in the discussion that NICs may implement different variations of rate-limiting in addition to drops, for example, queueing, which can be observed by users, but may be less impactful in some cases than drops.

Looking for your feedback on whether the suggestion to add a "queued" counter may benefit virtio as well.
[See also Parav's last comment in https://lore.kernel.org/netdev/20240827110402.0c8c5fc6@kernel.org/T/#m7ec54021c39a635fc047653151490f8ebc21ba7a]

**Comment by paravmellanox** [comment]
Following commit fixes this issue:
42f3899 virtio-net: support device stats
